# example netlify.toml
[build]
    command = "npm run build"
    functions = "netlify/functions"
    publish = ".next"

[[plugins]]
    package = "@netlify/plugin-next.js"

[functions]
  included_files = [".next/*.json"]